name: generate-and-send-coverage-report
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
jobs:
  run-test-task-and-send-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cypress tests
        run: |
          npm install
          npm run test:cy
      - name: Run codacy-coverage-reporter
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Javascript -r lcov.info
      
