name: Node Build
on:
  push:
    branches:
      [master, development]
  pull_request:
    branches: 
      [master, development]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        run: |
          npm install
      - uses: actions/upload-artifact@master
        with:
          name: angular artifacts
          path: public/
          
  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2016]
        node-version: [12.x, 14.x]
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: angular artifacts
          path: public
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: npm test
        run: |
          npm test
        env:
          CI: true
